import type { GetStaticProps, GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import { TempVisualizationChart } from "../components/temp-visualization-chart";

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  try {
    const res = await fetch("http://localhost:4000/temparetures");
    const { success, data }: Responsedata = await res.json();

    return {
      props: { data, success },
      revalidate: 10,
    };
  } catch (error) {
    return {
      props: { success: false },
    };
  }
};

const Home: NextPage<Responsedata> = ({ success, data }) => {
  console.log(data);

  return (
    <div>
      <Head>
        <title>IOT App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{success ? <TempVisualizationChart /> : ""}</main>
    </div>
  );
};

export default Home;
