import type { GetStaticProps, GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import { TempVisualizationChart } from "../components/temp-visualization-chart";
import ParentSize from "@visx/responsive/lib/components/ParentSize";

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  try {
    const res = await fetch("http://localhost:4000/temparetures");
    const { success, data }: Responsedata = await res.json();

    return {
      props: { data, success },
      revalidate: 10,
    };
  } catch (error) {
    return {
      props: { success: false },
    };
  }
};

const Home: NextPage<Responsedata> = ({ success, data }) => {
  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>IOT App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {success && data ? (
          <ParentSize>
            {({ width, height }) => (
              <TempVisualizationChart
                data={data as IData[]}
                width={width}
                height={height}
              />
            )}
          </ParentSize>
        ) : (
          ""
        )}
      </main>
    </div>
  );
};

export default Home;
